const emailActionTypes = {
  DATA_LOADING_START: "DATA_LOADING_START",
  DATA_LOADING_SUCCESS: "DATA_LOADING_SUCCESS",
  DATA_LOADING_FAIL: "DATA_LOADING_FAIL",
  DATA_SENDING_START: "DATA_SENDING_START",
  DATA_SENDING_SUCCESS: "DATA_SENDING_SUCCESS",
  DATA_SENDING_FAIL: "DATA_SENDING_FAIL",
  EMAIL_DETAILS_REQUEST: "EMAIL_DETAILS_REQUEST",
  EMAIL_DETAILS_SUCCESS: "EMAIL_DETAILS_SUCCESS",
  EMAIL_DETAILS_FAIL: "EMAIL_DETAILS_FAIL",
  EMAIL_DELETE_REQUEST: "EMAIL_DELETE_REQUEST",
  EMAIL_DELETE_SUCCESS: "EMAIL_DELETE_SUCCESS",
  EMAIL_DELETE_FAIL: "EMAIL_DELETE_FAIL",
  UPDATE_EMAIL: "UPDATE_EMAIL",
};

export default emailActionTypes;
